version: '3.9'
services:
  gateway:
    build:
      context: .
    container_name: 'gateway'
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
            - main


networks:
    main:
            external:
                    name: main
