// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/mzhn-sochi/gateway/internal/config"
	"github.com/mzhn-sochi/gateway/internal/controllers"
	"github.com/mzhn-sochi/gateway/internal/logger"
	"github.com/mzhn-sochi/gateway/internal/service/analyzerservice"
)

// Injectors from wire.go:

func InitApp() *App {
	configConfig := config.New()
	slogLogger := logger.New(configConfig)
	service := analyzerservice.New(configConfig, slogLogger)
	analyzerController := controllers.NewAnalyzerController(service)
	app := newApp(configConfig, slogLogger, analyzerController)
	return app
}
