// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: suggestions.proto

package shop_suggestions

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShopSuggestionsServiceClient is the client API for ShopSuggestionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShopSuggestionsServiceClient interface {
	GetSuggestion(ctx context.Context, in *SuggestionOptions, opts ...grpc.CallOption) (*ShopSuggestionsResponse, error)
}

type shopSuggestionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopSuggestionsServiceClient(cc grpc.ClientConnInterface) ShopSuggestionsServiceClient {
	return &shopSuggestionsServiceClient{cc}
}

func (c *shopSuggestionsServiceClient) GetSuggestion(ctx context.Context, in *SuggestionOptions, opts ...grpc.CallOption) (*ShopSuggestionsResponse, error) {
	out := new(ShopSuggestionsResponse)
	err := c.cc.Invoke(ctx, "/ShopSuggestionsService/GetSuggestion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopSuggestionsServiceServer is the server API for ShopSuggestionsService service.
// All implementations must embed UnimplementedShopSuggestionsServiceServer
// for forward compatibility
type ShopSuggestionsServiceServer interface {
	GetSuggestion(context.Context, *SuggestionOptions) (*ShopSuggestionsResponse, error)
	mustEmbedUnimplementedShopSuggestionsServiceServer()
}

// UnimplementedShopSuggestionsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShopSuggestionsServiceServer struct {
}

func (UnimplementedShopSuggestionsServiceServer) GetSuggestion(context.Context, *SuggestionOptions) (*ShopSuggestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuggestion not implemented")
}
func (UnimplementedShopSuggestionsServiceServer) mustEmbedUnimplementedShopSuggestionsServiceServer() {
}

// UnsafeShopSuggestionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShopSuggestionsServiceServer will
// result in compilation errors.
type UnsafeShopSuggestionsServiceServer interface {
	mustEmbedUnimplementedShopSuggestionsServiceServer()
}

func RegisterShopSuggestionsServiceServer(s grpc.ServiceRegistrar, srv ShopSuggestionsServiceServer) {
	s.RegisterService(&ShopSuggestionsService_ServiceDesc, srv)
}

func _ShopSuggestionsService_GetSuggestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestionOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopSuggestionsServiceServer).GetSuggestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShopSuggestionsService/GetSuggestion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopSuggestionsServiceServer).GetSuggestion(ctx, req.(*SuggestionOptions))
	}
	return interceptor(ctx, in, info, handler)
}

// ShopSuggestionsService_ServiceDesc is the grpc.ServiceDesc for ShopSuggestionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShopSuggestionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ShopSuggestionsService",
	HandlerType: (*ShopSuggestionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSuggestion",
			Handler:    _ShopSuggestionsService_GetSuggestion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "suggestions.proto",
}
